### ISSUE TITLE
Suggestion: support `--with-profile=profilename`

### ISSUE THREAD

**Issue by garrison** [plexus/chemacs#10]
This package is great.

My only suggestion would be to allow `--with-profile=profilename` as an alternative to `--with-profile profilename`.  Right now doing the former does not set the profile correctly.  Many packages, including emacs, use the `--option=value` syntax; see e.g. `--color=MODE` in `emacs --help`.  It would be great to support this since it may be a habit for many people (myself included).

**Comment by plexus** [comment]
Hi Jim,

That sounds like a good idea. I'd be very happy to merge such a pull request.
