### ISSUE TITLE
.emacs-profiles.el

### ISSUE THREAD

**Issue by wangms168** [plexus/chemacs#13]
in the .emacs-profiles.el
("my-spacemacs" . ((user-emacs-directory . "~/.emacs-init/my-spacemacs")
		     (env . (("SPACEMACSDIR" . "~/.emacs-init/my-spacemacs/.spacemacs.d")))))

Written

("my-spacemacs" . ((user-emacs-directory . "~/.emacs-init/my-spacemacs")
           (env . (("SPACEMACSDIR" . (concat user-emacs-directory ".spacsmacs.d"))))))

why not？

**Comment by plexus** [comment]
Hi @wangms168, the values for the env vars are not evaluated, so you can't use `concat` there. Just put in the whole string.

**Comment by wangms168** [comment]
Thank you
