### ISSUE TITLE
realpath issue in install script

### ISSUE THREAD

**Issue by Nathanael8** [plexus/chemacs#26]
Hi,

I tried to install chemacs on a macOS Catalina 10.15.3 but something didn't work:
I ran `./install.sh` and I got as response
```
./install.sh: line 3: realpath: command not found
OK	Creating symlink ~/.emacs -> /.emacs
```

and the symlink `~/.emacs` is broken. I guess I can just fix it by manually create the symlink, but I wanted to inform you that there is something wrong.

**Comment by plexus** [comment]
Ugh it seems @Yumasi's changes made things incompatible with OS X. I'll see what I can do, might have to revert.

**Comment by plexus** [comment]
@Nathanael8 I pushed a fix, would you mind trying that out?

**Comment by Nathanael8** [comment]
sorry for my late response I already created the symlink manually on my user. However I tried it with a new user and the installation script worked fine.
