### ISSUE TITLE
Is there a reason to use ".emacs" instead of ".emacs.d"?

### ISSUE THREAD

**Issue by alienbogart** [plexus/chemacs#30]
I'm really just curious if there's any advantage in doing so.

**Comment by plexus** [comment]
The idea is that you install chemacs in .emacs so you can have your own default config in .emacs.d.

**Comment by emacs18** [comment]
Also I think emacs looks for and uses one these files in this order:
- ~/.emacs.el
- ~/.emacs
- ~/.emacs.d/init.el

If chemacs used `~/.emacs.d/init.el` instead, then what would happen if user accidentally created `~/.emacs`?
By using `~/.emacs` which is higher in priority, I think it increases the chance of chemacs working as intended in more situations.
