### ISSUE TITLE
Scrollbar & toolbar showing when using Doom + Chemacs

### ISSUE THREAD

**Issue by jakebox** [plexus/chemacs#42]
Looks like when I run Doom with Chemacs the toolbar and scrollbar enable on startup, which isn't right. I can manually turn them off, but setting the variable doesn't seem to help at all. Seems like others have had the same problem: https://github.com/hlissner/doom-emacs/issues/2354.

**Emacs version:** 27.1
Running **emacs-plus** on **MacOS**, installed with homebrew. Latest Doom emacs. Also running latest Spacemacs but there's no issue there.

Just thought I'd submit and see if anyone has a fix. Thanks!

**Comment by plexus** [comment]
You should probably switch to Chemacs 2.

**Comment by jakebox** [comment]
Feel a bit foolish for opening and closing so quickly, maybe I can at least help someone else... Chemacs2 https://github.com/plexus/chemacs2 solved my problem and still works perfectly. Strayed off because it seemed in beta. Thanks!

Edit: And thanks for the quick reply.

**Comment by plexus** [comment]
Chemacs 2 has support for `early-init.el`, Chemacs 1 does not. A common use for early-init is disabling UI elements early on, so that explains what you are seeing. Spread the word! :)
